### ISSUE TITLE
tracking herb/mining?

### ISSUE THREAD

**Issue by falconmick** [michaelnpsp/KiwiFarm#10]
It doesn't seem to track farming of herbs or mines, am i doing somthing wrong? just scanned AH

**Comment by michaelnpsp** [comment]
<del>KiwiFarm does not track hegb/mining  only loot from mobs.</del>
KiwiFarm should track herb/mining,  maybe you have not defined a price source for the items, you have to go to the statistics section, select the submenu session, or zone or totals, search the item in "items looted" subseccion and assign a specific price or a price source.
