### ISSUE TITLE
WoW Classic - Current version 1.13.4.33920 - 4/18/2020 - Atiesh Server

### ISSUE THREAD

**Issue by jlspeeddragon** [michaelnpsp/KiwiFarm#2]
As of the above date and version, Kiwifarm is no longer working for me in WoW Classic.

I have tried deleting all WTF Files, removing and manully reinstalling kiwifarm into the addon folder directory (yes i know how to correctly DL, extract and place the correct folder), and /reload

CUrrent Kiwifarm issues:
- does not show up in the addon list at the character login screen on any character
- not showing up in the addons list when logged into any character 
- Not listed in the interface option > addon list.
- Not showing the minimap icon
- Any and all /Kfarm commands does not function - getting the default /help game info message

**Comment by michaelnpsp** [comment]
A working addon is not even needed in order to see the addon in the addons list only a **KiwiFarm.toc** file must exists in 

**_classic_\Interface\AddOns\KiwiFarm**

folder. So i bet the addon is not installed in the correct folder.
