### ISSUE TITLE
wow classic problem!

### ISSUE THREAD

**Issue by yadgen** [michaelnpsp/KiwiFarm#3]
Only when the team members are all outside the copy, the reset will have an effect. If you can fix this problem, the captain reset can change, thank you!

**Comment by michaelnpsp** [comment]
I don't understand this issue.  It's not possible to reset the instance if a member is inside, this cannot be avoided. 
Or maybe do you want the option disabled if a reset is not possible ? Sorry but It is very difficult to detect this case, a reset will reset all game instances, its not possible to know in advance which instance you want to reset.

**Comment by yadgen** [comment]
If there is a member inside, the captain resets outside the copy, the prompt message "Cannot reset ...", the actual situation has been successfully reset, but the number of times for this plugin has not changed.

**Comment by michaelnpsp** [comment]
Umm, You say the game is printing "cannot reset", but the addon must assume the reset was successfully ? The addon simply waits for the reset message "Instance Name has been reset", if the message is different i see no reason to increase the reset count.

**Comment by yadgen** [comment]
However, it has been reset successfully!

**Comment by michaelnpsp** [comment]
But if the game message sometimes  is wrong the issue is not fixable. how can i tell when the game is lying ?

**Comment by yadgen** [comment]
Is it possible to solve this problem in this way? Add a switch option?

**Comment by yadgen** [comment]
Force to reduce the number of resets or decide based on game messages.

**Comment by yadgen** [comment]
With the addition of this switch, I believe many people will have such needs.

**Comment by michaelnpsp** [comment]
Can you confirm the error message is ?:
"Cannot reset INSTANCE_NAME. There are players still inside the instance."

**Comment by yadgen** [comment]
> Can you confirm the error message is ?:
> "Cannot reset INSTANCE_NAME. There are players still inside the instance."

Yes i confirm.
The actual situation is that the instance has been reset.

**Comment by michaelnpsp** [comment]
You can download version 1.6 from curseforge, now for classic version kiwifarm assumes the reset was  sucesfully when the "players still inside the instance" message is displayed.
But im not sure about this issue,  the fix maybe be reverted or changed in a future patch.

**Comment by yadgen** [comment]
thanks！

michaelnpsp <notifications@github.com>于2020年4月29日 周三03:43写道：

**Comment by yadgen** [comment]
Tried it today, it was perfect, thank you!
