### ISSUE TITLE
Team to speak?

### ISSUE THREAD

**Issue by yadgen** [michaelnpsp/KiwiFarm#4]
Hi, Can I set the team to speak when resetting the instance? Thank you!

**Comment by michaelnpsp** [comment]
I don't understand what you mean. What is "team to speak" ?

**Comment by yadgen** [comment]
When resetting, i can send a sentence in the team to inform the team members that the instance has been reset.

**Comment by yadgen** [comment]
I hope that it is sent on reset, not manually.

**Comment by yadgen** [comment]
Can the text be customized?

**Comment by yadgen** [comment]
`SendChatMessage("副本已重置，请进入副本~" , "PARTY", nil);`
Reset instance, this code add where?

**Comment by yadgen** [comment]
I modified it myself, thank you.
