### ISSUE TITLE
Limit 32 copies in 24 hours？

### ISSUE THREAD

**Issue by yadgen** [michaelnpsp/KiwiFarm#6]
Hello, using your plug-in, very good, World of Warcraft nostalgic hidden update, you can only enter the copy 32 times in 24 hours, can you update this feature? Thank you very much for your support.

**Comment by michaelnpsp** [comment]
In version 1.10-classic i added a rudimentary tracking for the new classic limit. 
Its far from perfect, im tracking 30 resets per 24 hours, but i think the new system does not only involve "resets" (for example big raids have no manual resets, so the addon is not correctly tracking these raids).

**Comment by yadgen** [comment]
got it, thank you.
